controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    system_traction_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

system_traction_velocity_controller:
  ros__parameters:
    joints:
      - system_traction_joint
