// visibility_control.h
#ifndef CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER__VISIBILITY_CONTROL_H_
#define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_EXPORT __attribute__ ((dllexport))
    #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_IMPORT __attribute__ ((dllimport))
  #else
    #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_EXPORT __declspec(dllexport)
    #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_IMPORT __declspec(dllimport)
  #endif
  #ifdef CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_BUILDING_DLL
    #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_PUBLIC CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_EXPORT
  #else
    #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_PUBLIC CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_IMPORT
  #endif
  #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_PUBLIC_TYPE CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_PUBLIC
  #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_LOCAL
#else
  #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_EXPORT __attribute__ ((visibility("default")))
  #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_IMPORT
  #if __GNUC__ >= 4
    #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_PUBLIC __attribute__ ((visibility("default")))
    #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_PUBLIC
    #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_LOCAL
  #endif
  #define CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER_PUBLIC_TYPE
#endif

#endif  // CADDY_AI2_ROS2_CONTROL_HARDWARE_CURTIS_MOTOR_DRIVER__VISIBILITY_CONTROL_H_